vuetify/Home.js
vuejs-fr/vuetifyjs.com pull request #6
Opened 2018-03-10 20:51 UTC by Kocal

2018-03-12 08:12 UTC, MachinisteWeb requested changes
Quelques ajustements ! Super taff !

2018-03-12 08:12 UTC, Haeresis commented on lang/en/vuetify/Home.js
> +      text: 'Préparez-vous à une armada de composants spécialiés mis à votre disposition. Avec plus de 80 composants, il y a une solution pour chaque application.'
spécialisés

2018-03-12 08:12 UTC, Haeresis commented on lang/en/vuetify/Home.js
> +      text: "Lorsque vous rencontrez un obstacle, vous avez immédiatement besoin d'aide. Vuetify propose un support en ligne par chat grâce à la communauté grandissante de notre Discord."
sur notre Discord ?

2018-03-12 08:12 UTC, Haeresis commented on lang/en/vuetify/Home.js
> +    'Support du SSR and PWA',
SSR et PWA

2018-03-12 08:12 UTC, Haeresis commented on lang/en/vuetify/Home.js
> +    'Plus de 80+ composants Material Design',
Plus de 80 (sans le + du coup) ou 80+

2018-03-12 08:12 UTC, Haeresis commented on lang/en/vuetify/Home.js
> +    'Imports A La Carte',
Je mettrais « Imports à la carte » puisque en français « l'expression française » devient juste du français :)

2018-03-12 08:12 UTC, Haeresis commented on lang/en/vuetify/Home.js
> +    'Hey',
En fr je mettrais Hé

2018-03-12 08:12 UTC, Haeresis commented on lang/en/vuetify/Home.js
> +    "Je sais que choisir un framework front-end peut être une tâche décourageante -- il y a tellement d'options à prendre en compte et chacun d'entre eux se proclame d'être le meilleur. Donc vous dev
ce proclame être

2018-03-12 08:12 UTC, Haeresis commented on lang/en/vuetify/Home.js
> +    "Je sais que choisir un framework front-end peut être une tâche décourageante -- il y a tellement d'options à prendre en compte et chacun d'entre eux se proclame d'être le meilleur. Donc vous dev
vous même : « quels sont les métriques du succès ? » (oui je sais on l'utilise pas souvent mais c'est tout à fait approprié)

2018-03-12 08:12 UTC, Haeresis commented on lang/en/vuetify/Home.js
> +    "Je suis extrêmement touché que vous avez considéré à utiliser Vuetify en tant que votre prochain framework front-end. Beaucoup d'attention a été consacrée dans l'élaboration d'une configuration
> que vous ayez fait le choix de Vuetify pour votre prochain framework front-end 

? La phrase actuelle est super bancale :D

2018-03-12 08:12 UTC, Haeresis commented on lang/en/vuetify/Home.js
>    materialDesign: 'Material Design',
Peut être traduit par « matériel de conceptions » ou « ressource de conception ». Mais effectivement le terme original est parlant.

2018-03-12 08:34 UTC, Kocal commented on lang/en/vuetify/Home.js
> +    'Plus de 80+ composants Material Design',
Ah zut je l'avais zappé

2018-03-13 11:06 UTC, Haeresis commented
@Kocal, hésite pas me mentionner quand tu veux que je revois un truc que j'avais mis en « changes requested »

2018-03-13 11:13 UTC, Kocal commented
Yep @Haeresis ça roule, c'est juste qu'en fait j'étais occupé sur un autre [projet](https://github.com/Kocal/vuetify-algolia-places) :sweat_smile:.

Mais oui je n'hésiterai pas à te @ pour la prochaine review :)

2018-03-17 15:58 UTC, Kocal commented on lang/en/vuetify/Home.js
> +    "Je suis extrêmement touché que vous avez considéré à utiliser Vuetify en tant que votre prochain framework front-end. Beaucoup d'attention a été consacrée dans l'élaboration d'une configuration
:sweat_smile:

2018-03-17 16:25 UTC, Kocal commented
(et merci pour la review !!)

2018-03-18 10:34 UTC, MachinisteWeb approved these changes

2018-07-22 18:49 UTC, closed without merging