vuetify/Colors.js
vuejs-fr/vuetifyjs.com pull request #8
Opened 2018-03-11 17:54 UTC by Kocal

2018-03-12 08:19 UTC, MachinisteWeb requested changes
Quelques remarques. Bien joué !

2018-03-12 08:19 UTC, Haeresis commented on lang/en/style/Colors.js
> +  headerText: "Sans configuration, vous avez accès à toutes les couleurs de la [spécfication Material Design](https://material.io/guidelines/style/color.html) via **stylus** et **javascript**. Ces co
si tu l'as traduit plus tôt (sinon garde comme ça)

> coutes les couleurs des spécifications de la charte de conception

(ou de la spécification)

2018-03-12 08:19 UTC, Haeresis commented on lang/en/style/Colors.js
> +  alert: 'Vous **devez** configurer webpack pour utiliser `stylus`. Si vous utilisez un [template pré-concu](/getting-started/quick-start#new-applications) ça devrait déjà être bon pour vous.',
pré-conçu

2018-03-12 08:19 UTC, Haeresis commented on lang/en/style/Colors.js
> +  colorHeader: 'Couleurs Material',
Charte des couleurs

2018-03-12 08:19 UTC, Haeresis commented on lang/en/style/Colors.js
> +  colorText: 'Ci-dessous la liste des couleurs Material Design regroupées par couleur principale.',
de la charte de conception pour les couleurs regroupées

2018-03-12 08:19 UTC, Haeresis commented on lang/en/style/Colors.js
> +      text: 'Couleurs Material',
Charte des couleurs

2018-03-17 16:24 UTC, Kocal commented
Merci pour la review :+1:

2018-03-18 10:33 UTC, MachinisteWeb approved these changes

2018-07-22 18:49 UTC, closed without merging